/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viajes;

import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO DELL
 */
public class AgregarRuta extends javax.swing.JFrame {

    Inicio FormInicio;
    String Accion;
    /**
     * Creates new form AgregarCliente
     */
    
    public AgregarRuta() {
        //FormInicio = inicio;
        initComponents();
    }
    
    public AgregarRuta(Inicio inicio){
        FormInicio = inicio;
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        Accion = "ALTA";
        
    }
    
    public void setVisible(Ruta ruta,String accion){
        Accion = accion;
        if(Accion == "EDITAR"){
            txtEstadoOrigen.setText(ruta.EstadoOrigen);
            txtEstadoDestino.setText(ruta.EstadoDestino);
            txtCPOrigen.setText(ruta.CPOrigen + "");
            txtCPDestino.setText(ruta.CPDestino + "");
            txtKilometros.setText(ruta.Kilometros + "");
            btnGuardar.setText("Editar");
            setVisible(true);
        } 
        else if(Accion == "ELIMINAR"){
            txtEstadoOrigen.setText(ruta.EstadoOrigen);
            txtEstadoDestino.setText(ruta.EstadoDestino);
            txtCPOrigen.setText(ruta.CPOrigen + "");
            txtCPDestino.setText(ruta.CPDestino + "");
            txtKilometros.setText(ruta.Kilometros + "");
            btnGuardar.setText("Eliminar");
            setVisible(true);
            
            txtEstadoOrigen.setEnabled(false);
            txtEstadoDestino.setEnabled(false);
            txtCPOrigen.setEnabled(false);
            txtCPDestino.setEnabled(false);
            txtKilometros.setEnabled(false);
            btnGuardar.setText("Eliminar");
        }
    }
    
    public boolean isValid(Ruta ruta){
        boolean response = true;
        
        if( ( ruta.EstadoOrigen.trim().equals(ruta.EstadoDestino.trim())) || (ruta.CPOrigen == ruta.CPDestino)  )
        {
            response = false;
        }
        
        return response;
    }
    
    public boolean isNotDuplicate(Ruta ruta){
        boolean response = true;
        
        ArrayList<Ruta> rutas = FormInicio.GetRutas();
        for(int i = 0; i < rutas.size(); i++){
            Ruta r = rutas.get(i);
            if(
                    r.EstadoDestino.equals(ruta.EstadoDestino) && 
                    r.EstadoOrigen.equals(ruta.EstadoOrigen) && 
                    r.CPDestino == ruta.CPDestino &&
                    r.CPOrigen == ruta.CPOrigen && 
                    r.Kilometros == ruta.Kilometros)
            {
                response = true; 
                break;
            }
        }
        
        
        return response;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEstadoDestino = new javax.swing.JTextField();
        txtEstadoOrigen = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCPOrigen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCPDestino = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKilometros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setText("Estado Origen");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setText("Estado Destino");

        txtEstadoDestino.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N

        txtEstadoOrigen.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N

        btnCerrar.setBackground(new java.awt.Color(204, 204, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(204, 204, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("CP Origen");

        txtCPOrigen.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("CP Destino");

        txtCPDestino.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("Kilometros");

        txtKilometros.setFont(new java.awt.Font("Gill Sans MT", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 110, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtEstadoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPDestino)
                            .addComponent(txtCPOrigen)
                            .addComponent(txtEstadoDestino)
                            .addComponent(txtKilometros))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEstadoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEstadoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCPDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        try
        {
            String estadoOrigen = txtEstadoOrigen.getText();
            String estadoDestino = txtEstadoDestino.getText();
            int cpOrigen = Integer.parseInt(txtCPOrigen.getText());
            int cpDestino = Integer.parseInt(txtCPDestino.getText());
            double kilometros = Double.parseDouble(txtKilometros.getText());
            String estatus = "ACTIVO";
            Ruta ruta = new Ruta(estadoOrigen,estadoDestino,cpOrigen,cpDestino,kilometros,estatus);

            boolean isValido = isValid(ruta);
            boolean isNotDuplicated = isNotDuplicate(ruta);
            
            if(Accion == "ALTA"){
                if(!isNotDuplicated) throw new Exception("Ya existe un registro con esos datos");
                if(!isValido) throw new Exception("Los campos EstadoOrigen y EstadoDestino o CPOrigen y CPDestino no pueden ser iguales");
                FormInicio.GuardaRuta(ruta);
            }
            else if(Accion == "EDITAR"){
                if(!isNotDuplicated) throw new Exception("Ya existe un registro con esos datos");
                if(!isValido) throw new Exception("Los campos EstadoOrigen y EstadoDestino o CPOrigen y CPDestino no pueden ser iguales");
                FormInicio.EditaRuta(ruta);
            }
            else if(Accion == "ELIMINAR"){
                FormInicio.EliminaRuta(ruta);
            } 
            
        }
        catch(Exception error){
            JOptionPane.showMessageDialog(null, error.getMessage(), "Error al guardar el registro: ", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarRuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCPDestino;
    private javax.swing.JTextField txtCPOrigen;
    private javax.swing.JTextField txtEstadoDestino;
    private javax.swing.JTextField txtEstadoOrigen;
    private javax.swing.JTextField txtKilometros;
    // End of variables declaration//GEN-END:variables
}
